version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install --save'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:14.7.0    
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh $AZURE_VM_USER@$AZURE_VM_DNS "cd figapi && sudo npm run-script stop && sudo npm install && sudo npm start"

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
         requires:
          - hold