version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - run:
          name: "Build"
          command: "npm install"
  test:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - run:
          name: "Test"
          command: "npm test"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test